name: Generate Face Library

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 🚀 Run Script
        env:
         DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
         DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
         DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: python generate_json.py

      - name: Commit JSON
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@mail.com"
          git add facelibrary18.json
          git commit -m "update json" || echo "no change"
          git push
